
ARG IMAGE_BASE
ARG IMAGE_BOOST
ARG IMAGE_FFMPEG

FROM ${IMAGE_BOOST} as boost
FROM ${IMAGE_FFMPEG} as ffmpeg


FROM ${IMAGE_BASE} as build-app
	COPY --from=boost /opt/boost /opt/boost
	COPY --from=ffmpeg /opt/ffmpeg /opt/ffmpeg